import pyautogui as p
import time 
p.press("win")
time.sleep(1)
p.write("edge",interval=0.2)
p.press("enter")
time.sleep(3)
p.hotkey("ctrl","l")
p.write("youtube.com",interval=0.2)
p.press("enter")
time.sleep(3)
p.hotkey("/")
time.sleep(1)
p.write("apna collage", interval=0.2)
p.press("enter")
time.sleep(3)
p.click(width=1920, height=1080) 
